// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLu3CUC1SduH9QzKMaJCTuyc1-RqfCYw',
    appId: '1:456184968953:web:e383864dc04589ca8b9428',
    messagingSenderId: '456184968953',
    projectId: 'anniversary-tracker-app',
    authDomain: 'anniversary-tracker-app.firebaseapp.com',
    storageBucket: 'anniversary-tracker-app.firebasestorage.app',
    measurementId: 'G-72L952B23F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-_rM-OrM3b5_F_YGSLEZORCPUMu95RQ',
    appId: '1:456184968953:android:efc2a8d2b6ccc8498b9428',
    messagingSenderId: '456184968953',
    projectId: 'anniversary-tracker-app',
    storageBucket: 'anniversary-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8TZ4AeBlYh8ekB15Qj21aXJj_3rJYMnM',
    appId: '1:456184968953:ios:ceeec9d6059456ce8b9428',
    messagingSenderId: '456184968953',
    projectId: 'anniversary-tracker-app',
    storageBucket: 'anniversary-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

}